server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: agent-service
          uri: lb://agent-service
          predicates:
            - Path=/agent/**

        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/business/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**

        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hub/**

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

